apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources that make up this application
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Common labels applied to ALL resources
commonLabels:
  app: demo-app
  managed-by: harness-gitops
