apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
    managed-by: harness-gitops
spec:
  # Access the app with:  kubectl port-forward svc/demo-app 8080:80 -n demo
  type: NodePort
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
