apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-prod

resources:
  - ../../base

namePrefix: prod-

patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: demo-app

  - patch: |
      - op: replace
        path: /data/APP_ENV
        value: "production"
    target:
      kind: ConfigMap
      name: demo-app-html